### PR TITLE
Fix windows compilation errors

### PR DESCRIPTION
**Pull request by rivy**
This PR set fixes currrent windows compilation errors (see [AppVeyor build/test](https://ci.appveyor.com/project/rivy/rust-ansi-term/builds/26118094)) and increases backwards window version compatibility.

### CODE REVIEW

**Comment by rivy** [comment]
I can add an AppVeyor build status badge as well...

[Build status](https://ci.appveyor.com/project/ogham/rust-ansi-term) 

```
[![Build status](https://ci.appveyor.com/api/projects/status/q1of8msauxe0f8u6/branch/master?svg=true)](https://ci.appveyor.com/project/ogham/rust-ansi-term) 
```

But I'll need to know the AppVeyor assigned project tag (under <https://ci.appveyor.com/project/ogham/rust-ansi-term> \ Settings \ Badges; it'll replace the `q1of8msauxe0f8u6` tag).

**Comment by rivy** [comment]
Ping @ogham . Have you had a chance to look this over?

**Comment by Finomnis** [comment]
Yes, please merge this ASAP. The current version on crates.io is unusable on Windows.

**Comment by SirWindfield** [comment]
I changed the needed winapi features too in my PR #55. What do the other changes do? I could compile the project with just adding `fileapi`.

**Comment by rivy** [comment]
Further explanation, by commit, (notably, also explained in the commit messages)...

- [bcb89a2] fix ~ add missing winapi module feature ("fileapi")
  - fixes the baseline windows compilation issue
- [bc76cd1] fix 'long_and_detailed' test for `cfg!(windows)`
  - fixes failing test (which I thought initially was a windows issue, but is a differing `rustc` version issue)

... both of the above are required to get passing AppVeyor CI builds

- [093d0dd] fix minimum rust version
  - minimum rust version has increased based on changes (see commit notes for more explanation)
  - needed to define which versions to attempt with the AppVeyor builds
- [ed28592] refactor ~ load winapi constants into the `enable_ansi_support()`
  - refactors the constants to use names in the style already within the code
- [a4e42b7] change ~ increase windows early version compatibility
  - the prior windows change I PR'd created a dependency on Windows 8+, this pulls back and allows compilation for earlier Windows versions (7, ..., probably back to XP and Vista, although I haven't had any chance to test that far back)

I'm also going to be adding a commit which inserts an AppVeyor testing badge, so that failures are easier to see on the first page of the repo.

**Comment by SirWindfield** [comment]
Makes more sense to base my PR on yours tbh. I'll just rebase accordingly after @ogham merges.

**Comment by Finomnis** [comment]
Is @ogham even active any more?

**Comment by SirWindfield** [comment]
I created an organization where I merged the PRs of this crate. They can both live side by side. Just  specify the depndency as a git url. If this gets merged later on, you can switch back.

**Comment by SirWindfield** [comment]
Nice! I'll rebase my PR later on :)

**Comment by ogham** [comment]
Thanks for this; sorry it took me so long to get round to. I hope the Windows CI fares better this time.

Released as **v0.12.1**.

**Pull request merged**
