### PR TITLE
Bugfix: In the Display implementation of Infix, after a reset, use the correct style.

### PR DESCRIPTION
**Pull request by manuthambi**

### CODE REVIEW

**Comment by manuthambi** [comment]
I am not sure why the windows CI is failing. It seems to be something unrelated to what I am fixing.

**Comment by manuthambi** [comment]
I guess those problems are fixed in #52 ?

**Comment by ogham** [comment]
Thanks for this! I never noticed there was a bug.

(The Windows CI is a bit haphazard at the moment, but I verified that tests pass myself).

Released as **v0.12.1**.

**Comment by manuthambi** [comment]
Happy to help out. And thanks for making the release!

**Pull request merged**
