### PR TITLE
add no-op enable_ansi_support method for other platforms

### PR DESCRIPTION
**Pull request by mainrs**
This commit also moves the code base to the 2018 edition of Rust. This involved changing the import scheme of used modules. Crates do not need to be declared within lib.rs explicitly. The rather get pulled in as soon as they are imported via 'use' the first time.

### CODE REVIEW

**Comment by SirWindfield** [comment]
Is a minimum version of `1.17` still needed? If yes, I have to revert the move changes that ported the code to Rust 2018 edition.

**Comment by mainrs** [comment]
@ogham Appveyor will probably fail as the minimum Rust version is set to 1.28.0. Is this still required or can we move to 1.31.0, the first 2018 edition release? Feedback would be appreciated as I could then either fix the appveyor configuration file or revert my changes from moving to the 2018 edition.

**Comment by joshtriplett** [comment]
Please don't make unrelated changes (such as upgrading to Rust 2018) in the same PR (and in this case the same commit) as a new feature. I don't see any obvious reason why this feature depends on moving to 2018.

**Comment by joshtriplett** [comment]
Also, can you please doublecheck that all of the path changes need to happen? At least some of them should have worked unambiguously without needing further qualification.

**Comment by joshtriplett** [comment]
The no-op method proposed here seems like a good idea, to avoid conditionals in the calling code, and to allow for future compatibility with other platforms that may require initialization code.

**Comment by mainrs** [comment]
I will close this PR and open a new one just with the changes containing the noop.

**Pull request closed without merging**
