### PR TITLE
Explicitly set the VT processing ConsoleMode flag

### PR DESCRIPTION
**Pull request by deadalusai**
A small change to `enable_ansi_support` to query for the current ConsoleMode setting before optionally setting the `ENABLE_VIRTUAL_TERMINAL_PROCESSING` flag explicitly, if required.

This avoids accidentally overwriting any existing changes made to the ConsoleMode setting.

### CODE REVIEW

**Comment by deadalusai** [comment]
Worth noting that this operation still fails on Win8 or earlier (or Win10 earlier than build 10586?), with the error code `ERROR_INVALID_PARAMETER` (87).

**Comment by deadalusai** [comment]
@ogham any chance of getting this reviewed?

**Comment by ogham** [comment]
Hi,

I merged this in tonight after testing it on Windows. Thanks for including links to the Windows API -- it made it much easier to understand what was going on.

I'm sorry this took me so long to get around to. It should now be up as v0.11 on crates.io.

**Comment by deadalusai** [comment]
Thanks! 👍

**Pull request merged**
